name: main

on:
  push:
    branches:
      - main

jobs:
  main:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - windows-latest
          - ubuntu-latest
        python-version-windows:
          - "3.9"
          - "3.10"
          - "3.11"
        python-version-ubuntu:
          - "3.9"
          - "3.11"

    steps:
      - name: Set up Python
        if: matrix.os == 'windows-latest'
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version-windows }}

      - name: Set up Python
        if: matrix.os == 'ubuntu-latest'
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version-ubuntu }}

      - name: Update pip
        run: |
          python -m pip install --upgrade pip

      - name: Install flake8 and unittest
        run: |
          python -m pip install flake8

      - name: Display Python version
        run: python --version

      - name: Run flake8
        run: flake8

      - name: Run unittest
        run: python -m unittest test.py
